name: 'Setup Sisyphus'
description: 'Prepare "gradle.properties" needed by sisyphus build.'
inputs:
  github-token:
    description: 'Token to access GitHub APIs.'
    required: false

  developer:
    description: 'Sisyphus developer name.'
    required: false

  snapshot-repositories:
    description: 'Repositories to push snapshot artifact.'
    required: false
  release-repositories:
    description: 'Repositories to push release artifact.'
    required: false
  docker-repositories:
    description: 'Repositories to push docker images.'
    required: false
  npm-repositories:
    description: 'Repositories to push npm packages.'
    required: false
  config-repositories:
    description: 'Repositories to resolve config artifact dependencies.'
    required: false
  dependency-repositories:
    description: 'Repositories to resolve dependencies.'
    required: false

  config-artifacts:
    description: 'Config artifacts.'
    required: false

  gradle-portal-key:
    description: 'Key used for publishing plugin to gradle portal.'
    required: false
  gradle-portal-secret:
    description: 'Secret used for publishing plugin to gradle portal.'
    required: false
  gradle-jvm-args:
    description: 'Arguments for gradle jvm.'
    required: false

  gpg-key-name:
    description: 'Gnupg key name for signing.'
    required: false
runs:
  using: 'node12'
  main: 'dist/main/index.js'
  post: 'dist/post/index.js'
branding:
  icon: 'codesandbox'  
  color: 'blue'